FROM mcr.microsoft.com/playwright:v1.16.2-focal

ARG LOGIN_USERNAME
ENV LOGIN_USERNAME=${LOGIN_USERNAME}

ARG LOGIN_PASSWORD
ENV LOGIN_PASSWORD=${LOGIN_PASSWORD}

ARG TEST_EMAIL
ENV TEST_EMAIL=${TEST_EMAIL}

ARG MAILOSAUR_SERVER
ENV MAILOSAUR_SERVER=${MAILOSAUR_SERVER}

ARG MAILOSAUR_API_KEY
ENV MAILOSAUR_API_KEY=${MAILOSAUR_API_KEY}

ARG MAILOSAUR_DOMAIN
ENV MAILOSAUR_DOMAIN=${MAILOSAUR_DOMAIN}

ARG MAILOSAUR_PASSWORD
ENV MAILOSAUR_PASSWORD=${MAILOSAUR_PASSWORD}

COPY ./playwright /e2e
WORKDIR /e2e
RUN npm install
RUN npx playwright install
# Run playwright test
CMD [ "npx", "playwright", "test", "--reporter=list" ]
